apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: website-project
  namespace: argocd
spec:
  description: Website project
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
