apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website-application
  namespace: argocd
spec:
  project: website-project
  source:
    repoURL: https://github.com/lukaosmani/argocd-helm-website.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
