apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  repositories: |
    - url: https://github.com/lukaosmani/argocd-helm-website.git
