apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-website
  template:
    metadata:
      labels:
        app: my-website
    spec:
      containers:
        - name: website-blue
          image: "{{ .Values.websiteBlue.image.repository }}:{{ .Values.websiteBlue.image.tag }}"
          ports:
            - containerPort: {{ .Values.websiteBlue.containerPort }}
          env:
            - name: PORT
              value: "{{ .Values.websiteBlue.containerPort }}"
        - name: website-green
          image: "{{ .Values.websiteGreen.image.repository }}:{{ .Values.websiteGreen.image.tag }}"
          ports:
            - containerPort: {{ .Values.websiteGreen.containerPort }}
          env:
            - name: PORT
              value: "{{ .Values.websiteGreen.containerPort }}"
        - name: website-yellow
          image: "{{ .Values.websiteYellow.image.repository }}:{{ .Values.websiteYellow.image.tag }}"
          ports:
            - containerPort: {{ .Values.websiteYellow.containerPort }}
          env:
            - name: PORT
              value: "{{ .Values.websiteYellow.containerPort }}"
