apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.websiteColor }}
  labels:
    app: {{ .Release.Name }}
    websiteColor: {{ .Values.websiteColor }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      websiteColor: {{ .Values.websiteColor }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        websiteColor: {{ .Values.websiteColor }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
