apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  labels:
    app: website
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
{{- range $key, $value := .Values.websites }}
      - name: {{ $value.name }}
        image: {{ $value.image.repository }}:{{ $value.image.tag }}
        resources:
          limits:
            memory: {{ $value.resources.limits.memory }}
            cpu: {{ $value.resources.limits.cpu }}
          requests:
            memory: {{ $value.resources.requests.memory }}
            cpu: {{ $value.resources.requests.cpu }}
        ports:
        - containerPort: {{ $value.service.containerPort }}
{{- end }}
