apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-yellow
spec:
  replicas: {{ .Values.websiteYellow.replicaCount }}
  selector:
    matchLabels:
      app: website-yellow
  template:
    metadata:
      labels:
        app: website-yellow
    spec:
      containers:
        - name: website-yellow
          image: "{{ .Values.websiteYellow.image.repository }}:{{ .Values.websiteYellow.image.tag }}"
          ports:
            - containerPort: {{ .Values.websiteYellow.service.port }}
