apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.websiteColor }}-ingress
  labels:
    app: {{ .Release.Name }}
    websiteColor: {{ .Values.websiteColor }}
spec:
  rules:
    - host: {{ .Values.websiteColor }}.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.websiteColor }}-service
                port:
                  number: 80
