# templates/service-website-blue.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-website-blue
  labels:
    app: {{ .Release.Name }}-website-blue
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.websiteBlue.service.port }}
  selector:
    app: {{ .Release.Name }}-website-blue
