apiVersion: v1
kind: Service
metadata:
  name: website-green
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.websiteGreen.service.port }}
      targetPort: {{ .Values.websiteGreen.containerPort }}
  selector:
    app: my-website
