apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.websiteColor }}-service
  labels:
    app: {{ .Release.Name }}
    websiteColor: {{ .Values.websiteColor }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ .Release.Name }}
    websiteColor: {{ .Values.websiteColor }}
