{{- range $key, $value := .Values.websites }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $value.name }}-service
  labels:
    app: {{ $value.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ $value.name }}
  ports:
  - port: 80
    targetPort: {{ $value.service.containerPort }}
---
{{- end }}
