apiVersion: v1
kind: Service
metadata:
  name: website-green
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.websiteGreen.service.port }}
  selector:
    app: website-green
