apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-website.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "my-website.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "my-website.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
