apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website-blue
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-repo/argocd-helm-website'
    targetRevision: HEAD
    chart: my-website
    helm:
      valueFiles:
        - values-blue.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
