apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website-blue
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/lukaosmani/argocd-helm-website.git'
    targetRevision: HEAD
    path: my-website
    helm:
      valueFiles:
        - values-blue.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
