image:
  repository: lukaosmani/website
  tag: v1.0.0

environment: 
  name: default
  color: default

replicaCount: 3

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
