{{- range .Values.websites }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
  labels:
    app: {{ .name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .name }}
  ports:
  - port: {{ .service.port }}
    targetPort: {{ .service.port }}
{{- end }}
