# values.yaml

serviceAccount:
  create: true
  name: ""

# Define other components as well
websiteBlue:
  replicaCount: 1
  image:
    repository: lukaosmani/website-blue
    tag: v1.0.0
  service:
    port: 80

websiteGreen:
  replicaCount: 1
  image:
    repository: lukaosmani/website-green
    tag: v1.0.0
  service:
    port: 80

websiteYellow:
  replicaCount: 1
  image:
    repository: lukaosmani/website-yellow
    tag: v1.0.0
  service:
    port: 80
